"""Compress the control page into the firmware.

PlatformIO runs this before every build (see extra_scripts in
platformio.ini).  It reads data/index.html, splices in whichever tab icon
FAVICON selects, gzips the result and writes it as a C array into the build
directory, where web.cpp includes it.

Why gzip: the page is about 25 KB of text, and the board's web server sends
roughly one TCP segment per rendered frame -- so 25 KB was seventeen segments
and just over half a second, almost all of it waiting rather than working.
Compressed it is a quarter of that, and it costs the board nothing at runtime
because browsers have understood Content-Encoding: gzip for thirty years.

The generated header goes to the build directory rather than into src/: it is
output, and output does not belong in a source tree.
"""

from __future__ import annotations

import gzip
import os
import re
from typing import Any

Import("env")  # noqa: F821
env: Any

PROJECT: str = env.subst("$PROJECT_DIR")  # noqa: F821
BUILD: str = env.subst("$BUILD_DIR")  # noqa: F821
SOURCE: str = os.path.join(PROJECT, "data", "index.html")
FAVICON_H: str = os.path.join(PROJECT, "src", "favicon.h")
OUT: str = os.path.join(BUILD, "page_gz.h")


def selected_favicon() -> str:
    """Which icon FAVICON names, as a data: URI.

    The macros are read out of favicon.h rather than duplicated here, so the
    icons have exactly one definition and it is the one the C code uses.
    """
    src: str = open(FAVICON_H, encoding="utf-8").read()

    # -DFAVICON=FAVICON_EYES arrives as a CPPDEFINES tuple or a bare string.
    want: str = "FAVICON_FRANK"
    for define in env.get("CPPDEFINES", []):  # noqa: F821
        if isinstance(define, (list, tuple)) and len(define) == 2:
            if str(define[0]) == "FAVICON":
                want = str(define[1])

    name: str = "FAVICON_URI_EYES" if want.endswith("EYES") else "FAVICON_URI_FRANK"
    m = re.search(r"#define\s+" + name + r"\b(.*?)(?=\n#define|\n#if|\Z)",
                  src, re.S)
    if not m:
        raise SystemExit("gen_page: could not find %s in favicon.h" % name)
    # Adjacent string literals, concatenated the way the preprocessor would.
    parts: list[str] = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    if not parts:
        raise SystemExit("gen_page: %s has no string literals" % name)
    return "".join(parts)


def emit(data: bytes, raw_len: int, icon: str) -> str:
    lines: list[str] = [
        "// Generated by tools/gen_page.py -- do not edit.",
        "// Source: data/index.html (%d bytes, gzip %d, %.0f%%)"
        % (raw_len, len(data), 100.0 * len(data) / raw_len),
        "// Tab icon: %d bytes" % len(icon),
        "",
        "#ifndef PAGE_GZ_H",
        "#define PAGE_GZ_H",
        "",
        "#include <pgmspace.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "static const size_t PAGE_GZ_LEN = %d;" % len(data),
        "static const uint8_t PAGE_GZ[] PROGMEM = {",
    ]
    for i in range(0, len(data), 16):
        row = ", ".join("0x%02X" % b for b in data[i:i + 16])
        lines.append("    " + row + ",")
    lines += ["};", "", "#endif // PAGE_GZ_H", ""]
    return "\n".join(lines)


def main() -> None:
    html: str = open(SOURCE, encoding="utf-8").read()
    if "{{FAVICON}}" not in html:
        raise SystemExit("gen_page: data/index.html has no {{FAVICON}} marker")
    icon: str = selected_favicon()
    page: bytes = html.replace("{{FAVICON}}", icon).encode("utf-8")

    # mtime zeroed so an unchanged page produces an identical header and does
    # not force a rebuild of everything that includes it.
    packed: bytes = gzip.compress(page, compresslevel=9, mtime=0)

    header: str = emit(packed, len(page), icon)
    os.makedirs(BUILD, exist_ok=True)
    existing: str = ""
    if os.path.exists(OUT):
        existing = open(OUT, encoding="utf-8").read()
    if existing != header:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(header)

    print("page: %d bytes -> %d gzipped (%.0f%%), %d fewer TCP segments"
          % (len(page), len(packed), 100.0 * len(packed) / len(page),
             (len(page) - len(packed)) // 1460))


# web.cpp includes the generated header, so the build directory has to be on
# the include path.
env.Append(CPPPATH=[BUILD])  # noqa: F821
main()
